# Generated by Django 2.2.24 on 2021-06-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeHub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cfid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('mrating', models.IntegerField()),
                ('mrank', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('rank', models.CharField(max_length=100)),
            ],
        ),
    ]
