# Generated by Django 2.2.24 on 2021-06-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeHub', '0002_cfid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfid',
            name='cfusername',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
