# Generated by Django 2.2.24 on 2021-07-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodeHub', '0004_auto_20210619_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfid',
            name='no_of_a',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cfid',
            name='no_of_q',
            field=models.IntegerField(default=0),
        ),
    ]
