# Generated by Django 2.2.24 on 2021-08-20 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CodeHub', '0007_auto_20210808_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfid',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
